version: '3.1'

services:
  server:
    build: ./server
    restart: always
    ports:
      - '3333:3333'
    depends_on:
      - db
  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - server
    stdin_open: true
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data/db:/var/lib/pgsql
